# Generated by Django 2.0.3 on 2018-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50, verbose_name='Song Title')),
                ('album', models.CharField(default='No Album', max_length=50)),
                ('genre', models.CharField(default='others', max_length=10)),
                ('released_date', models.CharField(blank=True, max_length=20, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(default='cover_imge/image/no-img.jpg', upload_to='cover_image/')),
                ('uploader', models.CharField(max_length=20)),
            ],
        ),
    ]
