# Generated by Django 2.0.3 on 2018-07-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_userdownloadaudio_userdownloadvideo_userplayaudio_userplayvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyric', models.CharField(max_length=250)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Music')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='cover_image',
        ),
    ]
