# Generated by Django 2.0.3 on 2018-07-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_auto_20180717_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='lyric',
            field=models.TextField(),
        ),
    ]
