# Generated by Django 2.0.3 on 2018-07-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_auto_20180717_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='music',
            name='featured_artist',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
