# Generated by Django 2.0.3 on 2018-07-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_auto_20180717_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='music',
            name='featured_artist',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
