# Generated by Django 2.0.3 on 2018-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_auto_20180718_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(max_length=50),
        ),
    ]
