# Generated by Django 2.0.3 on 2018-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0011_confirmemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='slug_title',
            field=models.CharField(default='clean me', max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_title',
            field=models.CharField(default='clean me', max_length=300),
        ),
    ]
