# Generated by Django 2.0.3 on 2018-09-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0012_auto_20180927_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='slug_title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug_title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
