# Generated by Django 2.0.3 on 2018-10-01 09:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0017_auto_20181001_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtape',
            name='tracks',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
