# Generated by Django 2.0.3 on 2018-10-01 09:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0018_auto_20181001_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtape',
            name='dj_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
