# Generated by Django 2.0.3 on 2018-10-01 17:18

import Music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0020_auto_20181001_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtape',
            name='tape_image',
            field=models.FileField(upload_to=Music.models.user_directory_path),
        ),
    ]
