# Generated by Django 2.0.3 on 2018-07-30 11:27

import News.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20180730_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='cover_picture',
            field=models.ImageField(upload_to=News.models.user_directory_path),
        ),
    ]
