# Generated by Django 2.0.3 on 2018-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20180730_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='speaker',
            field=models.CharField(max_length=100),
        ),
    ]
