# Generated by Django 2.0.3 on 2018-09-21 11:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_auto_20180919_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
