# Generated by Django 2.0.3 on 2018-09-21 15:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20180921_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
    ]
