# Generated by Django 2.0.3 on 2018-08-30 01:30

import TalkZone.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=95)),
                ('subtitle', models.TextField()),
                ('slug', models.TextField()),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(upload_to=TalkZone.models.user_directory_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('poster', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='talkzone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
