# Generated by Django 2.0.3 on 2018-08-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkzone',
            name='description',
            field=models.TextField(default='clean me and key in desc'),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='subtitle',
            field=models.CharField(max_length=95),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='title',
            field=models.TextField(),
        ),
    ]
