# Generated by Django 2.0.3 on 2018-08-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0002_auto_20180830_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkzone',
            name='subtitle',
            field=models.CharField(max_length=96),
        ),
    ]
