# Generated by Django 2.0.3 on 2018-08-30 08:39

import TalkZone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0003_auto_20180830_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talkzone',
            old_name='body',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='talkzone',
            name='body2',
            field=models.TextField(default='clean me and type'),
        ),
        migrations.AddField(
            model_name='talkzone',
            name='middle_image',
            field=models.ImageField(default='clean me and put image', upload_to=TalkZone.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='description',
            field=models.TextField(default='clean me and type'),
        ),
    ]
