# Generated by Django 2.0.3 on 2018-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0004_auto_20180830_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkzone',
            name='subbody',
            field=models.CharField(default='clean me and type', max_length=200),
        ),
    ]
