# Generated by Django 2.0.3 on 2018-08-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('talk_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalkZone.TalkZone')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
