# Generated by Django 2.0.3 on 2018-10-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0007_auto_20180831_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='talk_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TalkZone.TalkZone'),
        ),
    ]
