# Generated by Django 2.0.3 on 2018-09-11 15:25

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(upload_to=Profile.models.user_directory_path),
        ),
    ]
