# Generated by Django 2.0.3 on 2018-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20180911_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(upload_to='cover_image'),
        ),
    ]
