# Generated by Django 2.0.3 on 2018-09-01 10:39

import Mysteries.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lovequote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('quote_picture', models.ImageField(upload_to=Mysteries.models.user_directory_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mysteries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
