# Generated by Django 2.0.3 on 2018-09-02 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mysteries', '0002_lovequote_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lovequote',
            new_name='Quote',
        ),
    ]
