# Generated by Django 2.0.3 on 2018-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gist', '0002_auto_20180730_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gistpost',
            name='seo_description',
        ),
        migrations.AddField(
            model_name='gistpost',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='gistpost',
            name='category',
            field=models.CharField(choices=[('comedy', 'COMEDY'), ('relationship', 'RELATIONSHIP'), ('gossip', 'GOSSIP')], default='comedy', max_length=250),
        ),
    ]
