# Generated by Django 2.0.3 on 2018-08-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gist', '0006_auto_20180813_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gistpost',
            name='category',
            field=models.CharField(choices=[('gossip', 'GOSSIP'), ('relationship', 'RELATIONSHIP'), ('wedding', 'WEDDING'), ('celeb', 'CELEB')], default='gossip', max_length=250),
        ),
    ]
