# Generated by Django 2.0.3 on 2018-09-28 10:14

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gist', '0008_mostview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gistpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='gistpost',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gistpost',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
    ]
