"""
Django settings for NaijaLatest project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from .email_info import *
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ngfncjll5%n^%q9t5cf+g9u23n%k&2c+#m79%w*dska+k&_6jo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT


# Application definition

INSTALLED_APPS = [
    'Music.apps.MusicConfig',
    'News.apps.NewsConfig',
    'Gist.apps.GistConfig',
    'Profile.apps.ProfileConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django_extensions',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'social_django',
    'TalkZone.apps.TalkzoneConfig',
    'Mysteries.apps.MysteriesConfig',
    'ckeditor',
    'ckeditor_uploader',

]
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'height': 300,
        'toolbar': 'default',
        'toolbar_default': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Strike',
             'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor0'],
            ['Smiley', 'specialChar'],
            ['Youtube'],
            ['Source'],
        ],
        'extraPlugins': 'youtube',


    },
    'special': {
        'toolbar': 'special',
        'height': 100,
        'toolbar_special': [
            ['Styles', 'Format', 'Bold', 'Italic', 'SpellChecker'],
            ['TextColor', 'BGColor'],
            ['SpecialChar'],
        ],
    },
    'specialtape':{
        'toolbar': 'specialtape',
        'toolbar_specialtape': [
            ['Image'],
        ],
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'NaijaLatest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'Music.context_processors.song',
                'Profile.context_processors.profile',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
    'social_core.backends.google.GoogleOpenId',  # for Google authentication
    'social_core.backends.google.GoogleOAuth2',  # for Google authentication
    'django.contrib.auth.backends.ModelBackend',

)
SOCIAL_AUTH_URL_NAMESPACE = 'social'
WSGI_APPLICATION = 'NaijaLatest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'music',
        'USER': 'postgres',
        'PASSWORD': 'onoyimaobia'
    }
}

SOCIAL_AUTH_POSTGRES_JSONFIELD = True
# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SHARE_URL = "http://127.0.0.1:9000/display_gist.html"
SHARE_TALKZONE_URL = "http://127.0.0.1:9000/talk_zone_view.html"
LOGIN_URL = 'profile/login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home1'

SOCIAL_AUTH_FACEBOOK_KEY = '276569669840426'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '36ffa2d12d0a1ed1c507b9223f1b4c9d'  # App Secret

SOCIAL_AUTH_GITHUB_KEY = '7d2c254958d044ac8997'
SOCIAL_AUTH_GITHUB_SECRET = '016fd2728b0c76e05b10691d480e9cf6111ac210'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ='742838240102-vc2av397nnkc7ope5sofba9eg43mgamm.apps.googleusercontent.com'  #Paste CLient Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'Ild3hdNdPwVSrfPq_rqsmXrQ' #Paste Secret Key
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'NaijaLatest/static'),
)


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

CONTENT_TYPES = ['image', 'video']
# 1.25MB = 1310720
# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 5242880
# 100MB 104857600
# 250MB - 214958080
# 500MB - 429916160
MAX_UPLOAD_SIZE = "1310720"

